# Generated by Django 5.2.4 on 2025-08-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('hours', models.TextField(verbose_name="Heures d'ouverture")),
                ('map_embed', models.TextField(blank=True, verbose_name='Code embed Google Maps')),
            ],
            options={
                'verbose_name': 'Informations de Contact',
                'verbose_name_plural': 'Informations de Contact',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
            ],
            options={
                'verbose_name': 'Avis Client',
                'verbose_name_plural': 'Avis Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
